apiVersion: apps/v1
kind: Deployment
metadata:
  name: kindapp
spec:
  selector:
    matchLabels:
      app: kindapp
  template:
    metadata:
      labels:
        app: kindapp
    spec:
      containers:
        - name: kindapp
          image: kindapp
          ports:
            - containerPort: 8080
          imagePullPolicy: Always