name: CD
on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Building package with Maven
        run: mvn -B package -DskipTests

      - name: Build and Push docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: paulosalonso
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: paulosalonso/kind
          tags: ${{ github.sha }}, latest

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1

      - name: Update K8S
        run: |
          cd .k8s
          kustomize edit set image kindapp=paulosalonso/kindapp:${{ github.sha }}
          cat kustomization.yml

      - name: Commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Deploy Action"
          git commit -am "Change image tag to paulosalonso/kindapp:${{ github.sha }}"

      - name: Push
        uses: ad-m/github-push-action@master