name: CD
on:
  push:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Building package with Maven
        run: mvn -B package -DskipTests

      - name: Build and Push docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: paulosalonso
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: paulosalonso/kind
          tags: ${{ github.sha }}, latest